# ////////////////////////////////////////////////////////////////////////////
# @brief docker registry image push or pulls
# @comment: needs to be separate from 'docker' because registry not set to work over ssh
# ////////////////////////////////////////////////////////////////////////////
- +local

# use given docker context
- docker context use $DCTX
- docker context ls

# automatic login to azure registry
- az acr login --name ${DOCKER_REGISTRY}
- echo "docker image is ${DOCKER_IMAGE_NAME}"

- pull:
  # pull the docker image from the azure registry
  # -- if slow connection, enabled the below option instead
  # - docker pull ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME} || docker pull ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}  || docker pull ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}  || true
  - docker pull ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME} || true

  # tag the azure registry docker image, as a non-registry prefix docker images
  - docker tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE_NAME} || true

- push:
  # tag the non-registry prefix docker images, as a azure registry docker image
  - docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME} || true
  # push the docker image to the azure registry
  - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME} || true

# remove the azure docker images
- docker-clean.bash ${DOCKER_REGISTRY}

# show the docker images
- docker images
# change the docker context back to the default docker daemon
- docker context use default
