# always create the default network if does not exist
- echo "Docker network subnet is $LOCAL_NETWORK_SUBNET"
- echo "Docker network ip range is $LOCAL_NETWORK_IP_RANGE"
- if [ ${INFRASTRUCTURE_SYSTEM} = "local" ]; then
    docker network create -d bridge robots --subnet=$LOCAL_NETWORK_SUBNET --ip-range=$LOCAL_NETWORK_IP_RANGE || true;
  fi

# start the docker create container service
- docker-compose-wrapper -p project-${DOCKER_COMPOSE_SERVICE} up --force-recreate -d ${DOCKER_COMPOSE_SERVICE}
