#!/usr/local/bin/perl

package cmpl_git;
use Exporter;
use FindBin;
use cmpl_utils;
use cmpl_help;
use Env;

# //////////////////////////////////////////////////////////////////////////////
# @brief export modules
# //////////////////////////////////////////////////////////////////////////////

our @ISA= qw( Exporter );

# these CAN be exported.
our @EXPORT_OK = qw(
  @_git
  @_git_help
);

# these are exported by default.
our @EXPORT = qw(
  @_git
  @_git_help
);

our (
  @_git,
  @_git_help
);

# read the deployer's cli matches (autogenerated by install-deployer.bash)
@_git = openfile("git.cmpl");

# //////////////////////////////////////////////////////////////////////////////
# @brief various help messages
# //////////////////////////////////////////////////////////////////////////////

# @brief assign help keys to usage messages as hashmap -- hack: convert array to hashmap
@_git_help = ({
  id      => "git",
  help    => create_help(get_help(qw(
    all_reset all_pull
    common_meta basestation_meta simulation_meta subt_launch_meta ugv_meta uav_meta perception_meta
    common_submodules basestation_submodules simulation_submodules subt_launch_submodules
    ugv_submodules uav_submodules perception_submodules
  ))),

# -- workspaces --
},{
  id      => "basestation",
  help    => create_help(get_help(qw(
    meta_checkout meta_ignore meta_unignore submodules_clean submodules_pull submodules_reset submodules_rm))),

},{
  id      => "common",
  help    => create_help(get_help(qw(
    meta_checkout meta_ignore meta_unignore submodules_clean submodules_pull submodules_reset submodules_rm))),

},{
  id      => "simulation",
  help    => create_help(get_help(qw(
    meta_checkout meta_ignore meta_unignore submodules_clean submodules_pull submodules_reset submodules_rm))),

},{
  id      => "uav",
  help    => create_help(get_help(qw(
    uav_meta uav_core_submodules uav_hardware_submodules))),

},{
  id      => "ugv",
  help    => create_help(get_help(qw(
    ugv_meta ugv_ppc_submodules ugv_nuc_submodules ugv_hardware_submodules ugv_slam_submodules))),

},{
  id      => "perception",
  help    => create_help(get_help(qw(
    meta_checkout meta_ignore meta_unignore submodules_clean submodules_pull submodules_reset submodules_rm))),

# -- actions --

},{
  id      => "meta",
  help    => create_help(get_help(qw(meta_checkout meta_ignore meta_unignore))),

},{
  id      => "submodules",
  help    => create_help(get_help(qw(submodules_clean submodules_pull submodules_reset submodules_rm))),

},{
  id      => "all",
  help    => create_help(get_help(qw(all_reset all_pull))),

});

