#!/usr/local/bin/perl

package cmpl_deployer;
use Exporter;
use FindBin;
use cmpl_utils;

# //////////////////////////////////////////////////////////////////////////////
# @brief export modules
# //////////////////////////////////////////////////////////////////////////////

our @ISA= qw( Exporter );

# these CAN be exported.
our @EXPORT_OK = qw(
  @_deployer
  $_deployer_local_help
  $_deployer_azure_help
  $_deployer_azure_ugv_help
  $_deployer_azure_uav_help
  $_deployer_robots_help
  $_deployer_robots_ugv_help
  $_deployer_robots_uav_help
  $_deployer_robots_ugv_computer_help
  $_deployer_commands_help
  $_deployer_commands_docker_help
  $_deployer_commands_catkin_help
  $_deployer_localhost_commands_help
  @_deployer_help_array
);

# these are exported by default.
our @EXPORT = qw(
  @_deployer
  $_deployer_local_help
  $_deployer_azure_help
  $_deployer_azure_ugv_help
  $_deployer_azure_uav_help
  $_deployer_robots_help
  $_deployer_robots_ugv_help
  $_deployer_robots_uav_help
  $_deployer_robots_ugv_computer_help
  $_deployer_commands_help
  $_deployer_commands_docker_help
  $_deployer_commands_catkin_help
  $_deployer_localhost_commands_help
  @_deployer_help_array
);

our (
  @_deployer,
  $_deployer_local_help,
  $_deployer_azure_help,
  $_deployer_azure_ugv_help,
  $_deployer_azure_uav_help,
  $_deployer_robots_help,
  $_deployer_robots_ugv_help,
  $_deployer_robots_uav_help,
  $_deployer_robots_ugv_computer_help,
  $_deployer_commands_help,
  $_deployer_commands_docker_help,
  $_deployer_commands_catkin_help,
  $_deployer_localhost_commands_help,
  @_deployer_help_array
);

# read the deployer's cli matches (autogenerated by install-deployer.bash)
@_deployer = openfile("deployer.cmpl");

# //////////////////////////////////////////////////////////////////////////////
# @brief various help messages
# //////////////////////////////////////////////////////////////////////////////

# local
$_deployer_local_help = ("
About: 1... deploys subt to localhost.
About: 2... your localhost runs the different parts of the system, in their own containers.
About: 4... this includes ugv (ground robot), uav (drone), basestation (gui) and perception (objdet).
About: 6... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 7... == Your Options Are ==
ugv          : deployment subt ugv on azure VMs.
uav          : deployment subt uav on azure VMs.
basestation  : deployment subt basestation on azure VMs.
perception   : deployment subt perception on azure VMs"
);
$_local_robots_ugv_help = ("
About: 1... deploys subt to any one of the local 'robot' docker containers.
About: 2... the same deploy is installed on all ground robots.
About: 3... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 4... == Your Options Are ==
Options:
ugv1       : deployment subt on ugv1 local docker container.
ugv2       : deployment subt on ugv2 local docker container.
ugv3       : deployment subt on ugv3 local docker container."
);
$_local_robots_uav_help = ("
About: 1... deploys subt to any one of the local 'robot' docker containers.
About: 2... the same deploy is installed on all drone robots.
About: 3... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 4... == Your Options Are ==
uav1       : deployment subt on uav1 Azure VM.
uav2       : deployment subt on uav2 Azure VM.
uav3       : deployment subt on uav3 Azure VM.
uav4       : deployment subt on uav4 Azure VM."
);
# azure
$_deployer_azure_help = ("
About: 1... deploys subt to Azure Virtual Machines (VMs).
About: 2... different VMs run different parts of the system.
About: 4... this includes ugv (ground robot), uav (drone), basestation (gui) and perception (objdet).
About: 5... the different systems run their own gazebo, rviz, etc, but can all communication with each other.
About: 6... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 7... == Your Options Are ==
ugv          : deployment subt ugv on azure VMs.
uav          : deployment subt uav on azure VMs.
basestation  : deployment subt basestation on azure VMs.
perception   : deployment subt perception on azure VMs"
);
$_deployer_azure_ugv_help = ("
About: 1... deploys subt to any one of the remote 'ground robot' Azure VMs.
About: 2... the same deploy is installed on all ground robot VMs.
About: 3... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 4... == Your Options Are ==
Options:
ugv1       : deployment subt on ugv1 Azure VM.
ugv2       : deployment subt on ugv2 Azure VM.
ugv3       : deployment subt on ugv3 Azure VM."
);
$_deployer_azure_uav_help = ("
About: 1... deploys subt to any one of the remote 'drone' Azure VMs.
About: 2... the same deploy is installed on all drone VMs.
About: 3... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 4... == Your Options Are ==
uav1       : deployment subt on uav1 Azure VM.
uav2       : deployment subt on uav2 Azure VM.
uav3       : deployment subt on uav3 Azure VM.
uav4       : deployment subt on uav4 Azure VM."
);
# robots
$_deployer_robots_help = ("
About: 1... deploys subt to one of the remote hardware robots or laptop basestation.
About: 2... different types of robots (and basestation) run different parts of the code.
About: 3... the same deploy is installed on all systems.
About: 4... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 5... == Your Options Are ==
basestation  : deployment subt on basestation.
ugv          : deployment subt on ugv hardware robots.
uav          : deployment subt on uav hardware robots."
);
$_deployer_robots_ugv_help = ("
About: 1... deploys subt to any one of the remote hardware ground robots.
About: 2... the ugvs have 3 different computers, to run different parts of the system.
About: 3... the same deploy is installed on all ground robots.
About: 4... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 5... == Your Options Are ==
ugv1       : deployment subt on ugv1 robot.
ugv2       : deployment subt on ugv2 robot.
ugv3       : deployment subt on ugv3 robot."
);
$_deployer_robots_uav_help = ("
About: 1... deploys subt to any one of the remote hardware drones.
About: 2... the same deploy is installed on all drone robots.
About: 3... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 4... == Your Options Are ==
ds1       : deployment subt on ds1 robot.
ds2       : deployment subt on ds2 robot.
ds3       : deployment subt on ds3 robot.
ds4       : deployment subt on ds4 robot."
);
$_deployer_robots_ugv_computer_help = ("
About: 1... deploys subt to any one of the remote hardware ground robots, to their specific computers.
About: 2... the ugvs have 3 different computers, to run different parts of the system.
About: 3... planning pc (ppc) runs the hardware, planning & comms stack.
About: 4... nuc runs state estimation stack.
About: 5... xavier runs perception stack.
About: 6... all three computers can communication with each other and can reach the basestation.
About: 7... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 8... == Your Options Are ==
ppc       : ppc ugv robot computer (hardware, planning, comms).
nuc       : nuc ugv robot computer (state estimation).
xavier    : xavier ugv robot computer (perception)."
);
# general commands
$_deployer_commands_help = ("
About: 1... general deployment operations commands.
About: 2... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 3... == Your Options Are ==
transfer.to  : transfers code from localhost to remote system (just an rsync).
skel_t.to    : transfers code (slim & faster -- no .git transfer) from localhost to remote system.
docker       : automated docker setup such as containers, images, registry pull.
catkin       : automated catkin build & clean for all catkin profiled workspaces."
);
$_deployer_commands_docker_help = ("
About: 1... general docker operation commands.
About: 2... you can add -p (preview) to show which deployment commands that will run.
About: 3... you can add -v (verbose) to show the exact shell commands that will be run.
About: 4... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 5... == Your Options Are ==
image                     : builds the docker image directly on the system.
shell                     : starts the docker container on the remote or local system.
rm                        : removes the docker container on the remote or local system.
stop                      : stops the docker container on the remote or local system.
registry.azure.pull       : pulls docker images from the azure registry to the remote or local system (needs internet).
registry.basestation.pull : pulls docker images from the basestation registry to the remote or local system (images need to already exist on the basestation).
network                   : creating or removing a user-defined docker network."
);
$_deployer_commands_catkin_help = ("
About: 1... general catkin operation commands.
About: 2... you can add -p (preview) to show which deployment commands that will run.
About: 3... you can add -v (verbose) to show the exact shell commands that will be run.
About: 4... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 5... == Your Options Are ==
build                     : catkin build (catkin profile workspace already pre-configured).
clean                     : catkin clean (catkin profile workspace already pre-configured)."
);
$_deployer_localhost_commands_help = ("
About: 1... general deployment operations commands.
About: 2... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 3... == Your Options Are ==
docker       : automated docker setup such as containers, images, registry pull.
catkin       : automated catkin build & clean for all catkin profiled workspaces."
);
$_deployer_type_commands_help = ("
About: 1... deploys the specific type of system dependencies (docker container enabled).
About: 2... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 3... == Your Options Are ==
cpu         : deploys subt using only the dependencies available for a CPU only system.
gpu         : deploys subt with dependencies optimized for a NVIDIA GPU available system."
);

$_deployer_uav_catkin_commands_help = ("
About: 1... general catkin commands, for difference types of catkin workspaces.
About: 2... * MAKE SURE THERE IS NO WHITESPACE WHEN YOU ADD THE NEXT OPTION (press backspace)
About: 3... == Your Options Are ==
clean         : cleans all the workspaces.
core          : builds or cleans the uav core workspace.
perception    : builds or cleans the uav perception workspace.
px4           : builds the px4 dependencies.
");

# @brief assign help keys to usage messages as hashmap -- hack: convert array to hashmap
@_deployer_help_array = ({
  id      => "local",
  help    => $_deployer_local_help,
},{
  id      => "local.ugv",
  help    => $_local_robots_ugv_help,
},{
  id      => "local.ugv.ugv1",
  help    => $_deployer_localhost_commands_help,
},{
  id      => "local.ugv.ugv2",
  help    => $_deployer_localhost_commands_help,
},{
  id      => "local.ugv.ugv3",
  help    => $_deployer_localhost_commands_help,
},{
  id      => "local.uav",
  help    => $_local_robots_uav_help,
},{
  id      => "local.uav.uav1",
  help    => $_deployer_type_commands_help,
},{
  id      => "local.uav.uav2",
  help    => $_deployer_type_commands_help,
},{
  id      => "local.uav.uav3",
  help    => $_deployer_type_commands_help,
},{
  id      => "local.uav.uav4",
  help    => $_deployer_type_commands_help,
},{
  id      => "local.basestation",
  help    => $_deployer_localhost_commands_help,
},{
  id      => "local.percpetion",
  help    => $_deployer_localhost_commands_help,
},{
  id      => "azure",
  help    => $_deployer_azure_help,
},{
  id      => "azure.ugv",
  help    => $_deployer_azure_ugv_help,
},{
  id      => "azure.ugv.ugv1",
  help    => $_deployer_commands_help,
},{
  id      => "azure.ugv.ugv2",
  help    => $_deployer_commands_help,
},{
  id      => "azure.ugv.ugv3",
  help    => $_deployer_commands_help,
},{
  id      => "azure.uav",
  help    => $_deployer_azure_uav_help,
},{
  id      => "azure.uav.uav1",
  help    => $_deployer_commands_help,
},{
  id      => "azure.uav.uav2",
  help    => $_deployer_commands_help,
},{
  id      => "azure.uav.uav3",
  help    => $_deployer_commands_help,
},{
  id      => "azure.uav.uav4",
  help    => $_deployer_commands_help,
},{
  id      => "robots",
  help    => $_deployer_robots_help
},{
  id      => "robots.ugv",
  help    => $_deployer_robots_ugv_help
},{
  id      => "robots.ugv.ugv1",
  help    => $_deployer_robots_ugv_computer_help
},{
  id      => "robots.ugv.ugv2",
  help    => $_deployer_robots_ugv_computer_help
},{
  id      => "robots.ugv.ugv3",
  help    => $_deployer_robots_ugv_computer_help
},{
  id      => "ppc",
  help    => $_deployer_commands_help
},{
  id      => "nuc",
  help    => $_deployer_commands_help
},{
  id      => "xavier",
  help    => $_deployer_commands_help
},{
  id      => "robots.uav.ds1",
  help    => $_deployer_commands_help
},{
  id      => "robots.uav.ds2",
  help    => $_deployer_commands_help
},{
  id      => "robots.uav.ds3",
  help    => $_deployer_commands_help
},{
  id      => "robots.uav.ds4",
  help    => $_deployer_commands_help
},{
  id      => "docker",
  help    => $_deployer_commands_docker_help
},{
  id      => "catkin",
  help    => $_deployer_uav_catkin_commands_help
},{
  id      => "catkin.core",
  help    => $ _deployer_commands_catkin_help
},{
  id      => "catkin.perception",
  help    => $_deployer_commands_catkin_help
},{
  id      => "cpu",
  help    => $_deployer_localhost_commands_help
},{
  id      => "gpu",
  help    => $_deployer_localhost_commands_help
});
