- cd $SUBT_PATH/

# export the second level meta submodule group
- export META_SECOND_LEVEL_PATH=perception
# export the third level meta to be the same the second level (since there are no sub-groups)
- export META_THIRD_LEVEL_GROUP_PATH=.

- meta:
  - +extend: common/git/actions/checkout
  - ignore:
    - +extend: common/git/actions/ignore
    # apply ignore on main workspace
    - ignore_catkin
    # apply ignore on nested workspace
    - export META_SECOND_LEVEL_PATH=perception/deps/catkin/
    - ignore_catkin

  - unignore:
    - +extend: common/git/actions/unignore
    # apply unignore on main workspace
    - unignore_catkin
    # apply unignore on nested workspace
    - export META_SECOND_LEVEL_PATH=perception/deps/catkin/
    - unignore_catkin

- submodules:
  - +extend: common/git/actions/pull
  - +extend: common/git/actions/reset
  - +extend: common/git/actions/rm
  - +extend: common/git/actions/clean

# apply the git action to the submodule sub-directory
- $GIT_ACTION_FUNCTOR

# export for top meta name for final cleanup
- export TOP_LEVEL_META=$SUBT_PATH/perception
