# set the exit command return value as a global (so upper deployer can exit on error return)
- set_last_command_exit_value() {
    if [[ $? -ne 0 ]]; then
      echo "...failed";
      export GL_LAST_COMMAND_FAILED=1;
      return 0;
    fi;
  }

# change directory to the given workspace workspace
- cd_workspace() {
    if [[ $GL_LAST_COMMAND_FAILED -eq 0 ]]; then
      cd $1;
      set_last_command_exit_value;
      echo "...cd $(pwd)";
    fi;
  }

# de-initialize submodules at the given, relative (to SUBT_PATH) workspace
- git_fetch() {
    if [[ $GL_LAST_COMMAND_FAILED -eq 0 ]]; then
      git fetch --all;
    fi;
  }

# fetch all branch updates in all submodules
- git_fetch_submodules() {
    if [[ $GL_LAST_COMMAND_FAILED -eq 0 ]]; then
      local topdir=$(pwd);
      for dirname in $(find . -type d -print); do
        echo "...fetch $topdir/$dirname";
        cd $topdir/$dirname;
        git fetch --all --prune;
        git sync;
      done;
    fi;
  }


# main entrypoint function: remove submodules
- git_rm() {
    local src_path=$(pwd);
    cd_workspace $META_SECOND_LEVEL_PATH;
    git_fetch $META_SECOND_LEVEL_PATH;
    cd_workspace $META_THIRD_LEVEL_GROUP_PATH;
    git_fetch_submodules;
    return $GL_LAST_COMMAND_FAILED;
  }

# export the git action function
- export GIT_ACTION_FUNCTOR=git_rm
