# set the exit command return value as a global (so upper deployer can exit on error return)
- set_last_command_exit_value() {
    if [[ $? -ne 0 ]]; then
      echo "...failed";
      export GL_LAST_COMMAND_FAILED=1;
      return 0;
    fi;
  }

# change directory to the given workspace workspace
- cd_workspace() {
    if [[ $GL_LAST_COMMAND_FAILED -eq 0 ]]; then
      cd $1;
      set_last_command_exit_value;
      echo "...cd $(pwd)";
    fi;
  }

# de-initialize submodules at the given, relative (to SUBT_PATH) workspace
- git_ignore() {
    if [[ $GL_LAST_COMMAND_FAILED -eq 0 ]]; then
      for filename in $(find .catkin_tools -type f -print); do
        echo "...ignore $filename";
        git update-index --assume-unchanged $filename > /dev/null 2>&1;
      done;
    fi;
  }

# clean submodules at the given workspace
- git_clean() {
    if [[ $GL_LAST_COMMAND_FAILED -eq 0 ]]; then
      echo "...cleanup catkin files";
      find . -type f -name "build.yaml" -delete;
      find . -type f -name "devel_collisions.txt" -delete;
      find . -type d -name "packages" -exec rm -rv {} +;
    fi;
  }

# main entrypoint function: remove submodules
- ignore_catkin () {
    local src_path=$(pwd);
    export GL_LAST_COMMAND_FAILED=0;
    echo "...ignore";
    cd_workspace $META_SECOND_LEVEL_PATH;
    git_clean;
    git_ignore;
    cd $src_path;
    return $GL_LAST_COMMAND_FAILED;
  }

# export the git action function
- export GIT_ACTION_FUNCTOR=ignore_catkin
