# //////////////////////////////////////////////////////////////////////////////
# @brief UGV, on Hardware Robots
# //////////////////////////////////////////////////////////////////////////////
version: '2.3'
services:

  # @brief UGV, base, ROS
  ugv.xavier-ros:
    image: ${DOCKER_IMAGE_NAME}
    build:
      context:    ${SUBT_DOCKERFILE_PATH}/
      dockerfile: ${SUBT_DOCKERFILE_PATH}/services/arm.base.ros.dockerfile
    extends:
      service: ${DOCKER_COMPOSE_BASE_SERVICE}
    container_name: ros-shell
    entrypoint: $entry_path/ros-shell.bash
    tty: true # keep container running

  # @brief UGV, planning-pc
  ugv.xavier-perception:
    image: ${DOCKER_IMAGE_NAME}
    build:
      context:    ${SUBT_DOCKERFILE_PATH}/
      # dockerfile: ${SUBT_DOCKERFILE_PATH}/services/arm.perception.dockerfile
      dockerfile: ${SUBT_DOCKERFILE_PATH}/services/arm.perception.supplement.dockerfile
    extends:
      service: ${DOCKER_COMPOSE_BASE_SERVICE}
    container_name: $ROBOT-perception-shell
    entrypoint: $entry_path/objdet-shell.bash
    privileged: true
    tty: true # keep container running
    environment:
      - ws_devel_source=$UGV_XAVIER_WS_SOURCE
    volumes:
      # Mount the flir and scd
      - /dev/subt:/dev/subt
