---
# ////////////////////////////////////////////////////////////////////////
# setup & install docker
# ////////////////////////////////////////////////////////////////////////
- name: remote robot ssh keys

  vars_files:
    - ../vars/main.yaml
    - ../vars/hosts.yaml
    - "{{ lookup('env','SUBT_CONFIGURATION_PATH') }}/ansible_config.yaml"

  # run playbook on the localhost
  hosts:
    - laptop
  become_method: sudo
  become_user: root

  # ////////////////////////////////////////////////////////////////////////
  # Tasks to execute
  # ////////////////////////////////////////////////////////////////////////
  tasks:
    - name: Remove any previous subt robot keys
      file:
        state: absent
        path: "~/.ssh/{{ robot_ssh_keys }}"

    - name: generate SSH key "{{ robot_ssh_keys }}"
      openssh_keypair:
        path: "~/.ssh/{{ robot_ssh_keys }}"
        type: rsa
        size: 4096
        state: present
        force: no

    - name: Add ssh key on remote hosts
      shell: ssh-copy-id -f -i ~/.ssh/{{ robot_ssh_keys }}.pub {{ item.host }}
      ignore_errors: yes
      with_items: " {{ ssh_config.hosts }} "
