#!/bin/bash

if [ $# -lt 1 ]; then
	echo "[Err] Too few args"
	exit 1
fi

for robot in $@
do
	echo "[$robot] executing following commands:"
	for session in $(tmux list-sessions | grep $robot | cut -f1 -d':')
	do
		cmd="tmux kill-session -t $session"
		echo $cmd
		eval $cmd
	done
done
